name: Deploy Chrome Extension

on:
  push:
    tags:
      - 'ChromeExtension_v.*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./extension

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Build extension
        run: npm run build:extension

      - name: Upload Chrome Extension Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chrome-extension
          path: ./extension/InNotes.zip

      - name: Upload to Chrome Web Store
        uses: mobilefirstllc/cws-publish@latest
        with:
          action: 'publish'  # one of: upload, publish, testers
          client_id: ${{ secrets.CHROME_WEB_STORE_CLIENT_ID }}
          client_secret: ${{ secrets.CHROME_WEB_STORE_CLIENT_SECRET }}
          refresh_token: ${{ secrets.CHROME_WEB_STORE_REFRESH_TOKEN }}
          extension_id: ${{ secrets.EXTENSION_ID }}
          zip_file: ./extension/InNotes.zip
